services:
  surreal:
    env_file:
      - .env
    image: surrealdb/surrealdb:latest
    container_name: tide-db
    volumes:
      - ./data/db:/data
    command:
      - start
      - --user=$DB_USER
      - --pass=$DB_PASS
      - rocksdb:/data/surreal.db
    restart: always
    networks:
      - www
  tide:
    env_file:
      - .env
    build: .
    container_name: tide
    restart: always
    networks:
      - www

networks:
  www:
    name: www
    external: true