services:
  surreal:
    env_file:
      - .env
    image: surrealdb/surrealdb:latest
    container_name: tide-db
    volumes:
      - ./data/db:/data
    user: root
    command:
      - start
      - rocksdb:/data/surreal.db
    restart: always
    networks:
      - www
  tide:
    env_file:
      - .env
    build: .
    volumes:
      - tide-vol:/app/data
    container_name: tide
    restart: always
    networks:
      - www

networks:
  www:
    name: www
    external: true

volumes:
  tide-vol:
    name: tide-vol