name: Docker Image CI
on:
    push:
        branches: [ "production" ]
    pull_request:
        branches: [ "production" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v4
         - name: Set up QEMU
           uses: docker/setup-qemu-action@v3
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
         - name: Build
           uses: docker/build-push-action@v6
           with:
                push: true
                tags: loshido/tidee:production
                secrets: |
                    "github_token=${{ secrets.HUB_TOKEN }}"
